# Generated by Django 6.0.7 on 2026-07-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Matn'), ('image', 'Rasm'), ('sticker', 'Stiker')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sticker',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
